# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-15 02:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog2', '0002_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='status',
            field=models.CharField(max_length=20, null=True, verbose_name='\u72b6\u6001'),
        ),
    ]
