# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-15 02:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog2', '0003_article_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='pub_usr',
            field=models.CharField(max_length=20, null=True, verbose_name='\u521b\u5efa\u4eba'),
        ),
    ]
