# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-15 03:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog2', '0004_article_pub_usr'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='color_code',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
