# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-14 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodeCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_convery', models.CharField(max_length=1000)),
                ('app_title', models.CharField(max_length=60)),
                ('upload_time', models.CharField(max_length=60)),
                ('app_desc', models.CharField(max_length=200)),
                ('category_txt_href', models.CharField(max_length=200)),
                ('app_category', models.CharField(max_length=20)),
            ],
        ),
    ]
