# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-16 00:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodeCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_convery', models.CharField(max_length=1000, verbose_name='\u6548\u679c\u56fe')),
                ('app_title', models.CharField(max_length=20, verbose_name='\u540d\u79f0')),
                ('upload_author', models.CharField(max_length=60, null=True, verbose_name='\u4e0a\u4f20')),
                ('update_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('app_desc', models.CharField(max_length=200, verbose_name='\u63cf\u8ff0')),
                ('category_txt_href', models.CharField(max_length=200, verbose_name='\u94fe\u63a5')),
                ('app_category', models.CharField(max_length=20, verbose_name='\u5206\u7c7b')),
            ],
        ),
    ]
