# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-16 00:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_23code', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codecategory',
            name='update_time',
        ),
        migrations.RemoveField(
            model_name='codecategory',
            name='upload_author',
        ),
        migrations.AddField(
            model_name='codecategory',
            name='upload_time',
            field=models.CharField(max_length=60, null=True, verbose_name='\u4e0a\u4f20\u65f6\u95f4'),
        ),
    ]
