# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-15 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_23code', '0002_auto_20161215_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codecategory',
            name='app_title',
            field=models.CharField(max_length=20, verbose_name='\u540d\u79f0'),
        ),
    ]
