# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-16 16:07
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_23code', '0002_auto_20161216_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codecategory',
            name='app_desc',
            field=DjangoUeditor.models.UEditorField(blank=True, default='', max_length=200, verbose_name='\u63cf\u8ff0'),
        ),
    ]
