# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-16 00:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_23code', '0002_auto_20161216_0842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codecategory',
            name='upload_time',
        ),
        migrations.AddField(
            model_name='codecategory',
            name='update_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='\u66f4\u65b0\u65f6\u95f4'),
        ),
        migrations.AddField(
            model_name='codecategory',
            name='upload_author',
            field=models.CharField(max_length=60, null=True, verbose_name='\u4e0a\u4f20'),
        ),
    ]
