# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-16 16:13
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_23code', '0003_auto_20161217_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codecategory',
            name='app_desc',
            field=DjangoUeditor.models.UEditorField(blank=True, default='', verbose_name='\u63cf\u8ff0'),
        ),
    ]
