# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-17 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=32, verbose_name='\u7528\u6237\u540d')),
                ('password', models.CharField(blank=True, max_length=50, verbose_name='\u5bc6\u7801')),
                ('domain', models.CharField(blank=True, help_text=b'\xe5\xa1\xab\xe5\x86\x99\xe5\xa4\x9a\xe4\xb8\xaa\xe5\x9f\x9f\xe5\x90\x8d\xef\xbc\x8c\xe4\xbb\xa5,\xe5\x8f\xb7\xe5\x88\x86\xe9\x9a\x94', max_length=256, verbose_name='\u53ef\u64cd\u4f5c\u57df\u540d')),
                ('is_active', models.IntegerField(blank=True, verbose_name='is_active')),
                ('phone', models.CharField(max_length=50, verbose_name='\u7535\u8bdd')),
                ('mail', models.CharField(max_length=50, verbose_name='\u90ae\u7bb1')),
            ],
        ),
    ]
