# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-17 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='check_password',
            field=models.CharField(max_length=50, null=True, verbose_name='\u786e\u8ba4\u5bc6\u7801'),
        ),
    ]
