# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-17 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0002_account_check_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='check_password',
        ),
        migrations.AddField(
            model_name='account',
            name='is_superuser',
            field=models.IntegerField(blank=True, null=True, verbose_name='is_superuser'),
        ),
    ]
