# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-17 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0004_account_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='\u7528\u6237\u521b\u5efa\u7684\u65e5\u671f'),
        ),
        migrations.AddField(
            model_name='account',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='\u4e0a\u6b21\u767b\u5f55\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='account',
            name='is_active',
            field=models.IntegerField(blank=True, default=True, verbose_name='is_active'),
        ),
        migrations.AlterField(
            model_name='account',
            name='is_staff',
            field=models.BooleanField(default=True, verbose_name='is_staff'),
        ),
        migrations.AlterField(
            model_name='account',
            name='is_superuser',
            field=models.BooleanField(default=True, verbose_name='is_superuser'),
        ),
    ]
