# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-17 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0005_auto_20161217_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='is_active',
            field=models.IntegerField(blank=True, default=False, verbose_name='is_active'),
        ),
    ]
